// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAltlxPXhwUZcUHEkGwQx8n6pEZD6Zodu8',
    appId: '1:737972637895:web:7e23a74a31d176c6f72ee2',
    messagingSenderId: '737972637895',
    projectId: 'fruitefubecommerceapp',
    authDomain: 'fruitefubecommerceapp.firebaseapp.com',
    storageBucket: 'fruitefubecommerceapp.appspot.com',
    measurementId: 'G-7SLH8E0YQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARjvEMCdwR-Vi0yqNj-ZUKTblRcY3azGk',
    appId: '1:737972637895:android:e7d12eca8d2737a5f72ee2',
    messagingSenderId: '737972637895',
    projectId: 'fruitefubecommerceapp',
    storageBucket: 'fruitefubecommerceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNcdc0AAoUbf1v2uN-HG5OIkvHbfUK1sY',
    appId: '1:737972637895:ios:7430f4462f25719df72ee2',
    messagingSenderId: '737972637895',
    projectId: 'fruitefubecommerceapp',
    storageBucket: 'fruitefubecommerceapp.appspot.com',
    iosBundleId: 'com.example.fruiteHubEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNcdc0AAoUbf1v2uN-HG5OIkvHbfUK1sY',
    appId: '1:737972637895:ios:7430f4462f25719df72ee2',
    messagingSenderId: '737972637895',
    projectId: 'fruitefubecommerceapp',
    storageBucket: 'fruitefubecommerceapp.appspot.com',
    iosBundleId: 'com.example.fruiteHubEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAltlxPXhwUZcUHEkGwQx8n6pEZD6Zodu8',
    appId: '1:737972637895:web:409e27ab0174ae87f72ee2',
    messagingSenderId: '737972637895',
    projectId: 'fruitefubecommerceapp',
    authDomain: 'fruitefubecommerceapp.firebaseapp.com',
    storageBucket: 'fruitefubecommerceapp.appspot.com',
    measurementId: 'G-9YXJ1KSFY1',
  );
}
